### ISSUE TITLE
[Design] Fragment_news 화면 제작 및 리사이클러뷰 연결

### ISSUE THREAD

**Issue by huiwoo-jo** [huiwoo-jo/MVVM_Project#15]
## Description
> news 목록을 출력하는 fragment_news의 리사이클러뷰 제작

## Todo
- [x] news model 제작
- [x] news view model 제작
- [x] news recycler view 설정
- [x] news item 제작
- [x] recycler view 연결

## ETC
해당 사항 없음
